SELECT
    ID,
    CASE
        WHEN P_ID IS NULL THEN 'ROOT'
        WHEN ID NOT IN ( SELECT P_ID FROM TREE WHERE P_ID IS NOT NULL ) THEN 'LEAF'
        ELSE 'INNER'
    END AS TYPE
FROM TREE
ORDER BY ID;